version: '3.7'

networks:
  sample-network:
    driver: bridge
    name: sample-network

services:
  crud-sample-database:
    image: mariadb:10
    networks:
      - sample-network
    ports:
      - 3306:3306
    volumes:
      - /D/data/docker/mariadb/data:/var/lib/mysql:rw
      - /D/data/docker/mariadb/logs:/var/log/mysql/
      - ../assembly:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1
