version: '3.7'

networks:
  bard-network:
    driver: bridge
    name: bard-network

services:
  bard-crud-sample-database:
    image: mysql:8
    volumes:
      - /data/bard-crud-sample-database/data:/var/lib/mysql:rw
      - /data/bard-crud-sample-database/logs:/var/log/mysql/
      - /etc/localtime:/etc/localtime:ro
        - ../assembly:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: bard-crud-sample
      MYSQL_USER: bard
      MYSQL_PASSWORD: 1
    ports:
      - 3306:3306
    networks:
      - bard-network
